<?php $productInfo = $this->_getProductInfo(); ?>
<?php if (!empty($productInfo)) : ?>
	<script type="text/javascript">
		// for product
		var _trboq = _trboq || [];
		_trboq.push([
			'productView',
			{
				products: [
					<?php echo json_encode($productInfo); ?>
				]
			}
		]);
        _trboq.push([
            'page',
            {
                type: 'detail'
            }
        ]);
	</script>
<?php endif; ?>

